# Generated by Django 5.2 on 2025-04-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pages',
            field=models.ManyToManyField(to='page.page'),
        ),
    ]
