# Generated by Django 5.2 on 2025-05-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('module', '0003_module_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='assignments',
            field=models.ManyToManyField(to='assignment.assignment'),
        ),
    ]
