# Generated by Django 5.2 on 2025-04-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_course_enrolled'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(to='module.module'),
        ),
    ]
